allowBuilds:
  esbuild: true
  sharp: false
  stockfish: true
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.76'
  - '@ai-sdk/provider-utils@5.0.37'
  - '@ai-sdk/provider@4.0.11'
  - ai@7.0.95
  - eve@0.52.4
