// src/app/dev/pages/page.tsx  [U4]
// Development-only harness for the four signed-in pages of UI_REDESIGN §6.
// Nobody can sign in during implementation or visual QA, so the presentational
// halves of /play, /leaderboard, /profile and /settings are rendered here with
// fixed data. The route does not exist in production.
//
// `?section=play|leaderboard|profile|settings` renders one slice on its own —
// the only way to screenshot the lower slices in a headless pane that composites
// a single frame per navigation.
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { PagesGallery } from "./gallery";
import { SECTION_IDS, type SectionId } from "./sections";

export const metadata: Metadata = {
  title: "Pages",
  robots: { index: false, follow: false },
};

function parseSection(raw: string | string[] | undefined): SectionId | null {
  const value = Array.isArray(raw) ? raw[0] : raw;
  return SECTION_IDS.includes(value as SectionId) ? (value as SectionId) : null;
}

export default async function PagesDevHarness({
  searchParams,
}: {
  // Spelt out rather than `PageProps<"/dev/pages">`: the typed-routes registry is
  // generated by `next build`/`next dev`, and a route added mid-session is not in
  // it yet, so `tsc --noEmit` would fail on a perfectly valid page.
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  if (process.env.NODE_ENV === "production") notFound();
  const { section } = await searchParams;
  return <PagesGallery only={parseSection(section)} />;
}
